#!/bin/bash

TOP_SRCDIR=$(cd $(dirname $0) && pwd)
export ARKI_SCAN_GRIB1=$TOP_SRCDIR/conf/scan-grib1/
export ARKI_SCAN_GRIB2=$TOP_SRCDIR/conf/scan-grib2/
export ARKI_FORMATTER=$TOP_SRCDIR/conf/format/
export ARKI_REPORT=$TOP_SRCDIR/conf/report/
export PATH="$TOP_SRCDIR/src:$PATH"
#export ARKI_POSTPROC=$TOP_SRCDIR/test/postproc

exec "$@"
