#!/bin/bash

TOP_SRCDIR=$(cd $(dirname $0) && pwd)
export ARKI_SCAN_GRIB1=$TOP_SRCDIR/conf/scan-grib1/
export ARKI_SCAN_GRIB2=$TOP_SRCDIR/conf/scan-grib2/
export ARKI_SCAN_BUFR=$TOP_SRCDIR/conf/scan-bufr/
export ARKI_SCAN_ODIMH5=$TOP_SRCDIR/conf/scan-odimh5/
export ARKI_FORMATTER=$TOP_SRCDIR/conf/format/
export ARKI_REPORT=$TOP_SRCDIR/conf/report/
export ARKI_BBOX=$TOP_SRCDIR/conf/bbox/
export ARKI_QMACRO=$TOP_SRCDIR/conf/qmacro/
export ARKI_TARGETFILE=$TOP_SRCDIR/conf/targetfile/
export ARKI_ALIASES=$TOP_SRCDIR/conf/match-alias.conf
export PATH="$TOP_SRCDIR/src:$PATH"
export ARKI_POSTPROC=$TOP_SRCDIR/test/postproc
export LD_LIBRARY_PATH="$TOP_SRCDIR/arki:$LD_LIBRARY_PATH"
export METEO_VM2_SOURCE="$TOP_SRCDIR/conf/vm2/source.lua"
export PYTHONPATH="$TOP_SRCDIR/python"

#ulimit -v 1048576

exec "$@"
