#!/bin/bash

TOP_SRCDIR=$(cd $(dirname $0) && pwd)
export ARKI_SCAN_GRIB1=$TOP_SRCDIR/conf/scan-grib1/
export ARKI_SCAN_GRIB2=$TOP_SRCDIR/conf/scan-grib2/
export ARKI_SCAN_BUFR=$TOP_SRCDIR/conf/scan-bufr/
export ARKI_FORMATTER=$TOP_SRCDIR/conf/format/
export ARKI_REPORT=$TOP_SRCDIR/conf/report/
export ARKI_BBOX=$TOP_SRCDIR/conf/bbox/
export ARKI_QMACRO=$TOP_SRCDIR/conf/qmacro/
export ARKI_TARGETFILE=$TOP_SRCDIR/conf/targetfile/
export ARKI_ALIASES=$TOP_SRCDIR/conf/match-alias.conf
export ARKI_SERVER=$TOP_SRCDIR/conf/server/
export PATH="$TOP_SRCDIR/src:$PATH"
#export ARKI_POSTPROC=$TOP_SRCDIR/test/postproc

exec "$@"
