#!/usr/bin/python3

import re
import os
import stat
import sys
import tarfile
import logging
import argparse

log = logging.getLogger()

def do_archive(src, rootpath=None):
    re_data = re.compile(r"(?:\.grib|\.grib1|\.grib2|\.vm2|\.odimh5|\.bufr|.repack)$")
    with tarfile.open(mode="w:gz", format=tarfile.PAX_FORMAT, fileobj=sys.stdout.buffer) as out:
        for root, dirnames, fnames, rootfd in os.fwalk(src):
            if rootpath is not None:
                root = os.path.relpath(root, rootpath)

            for fname in fnames:
                hfd = os.open(fname, os.O_RDONLY, dir_fd=rootfd)
                with os.fdopen(hfd, "rb") as fd:
                    info = out.gettarinfo(
                            arcname=os.path.join(root, fname),
                            fileobj=fd)

                    if re_data.search(fname):
                        info.pax_headers["hole"] = str(info.size)
                        info.size = 0
                        log.info("h %s", info.name)
                    else:
                        log.info("a %s", info.name)

                    out.addfile(info, fd)

def do_extract(src, rootpath=None):
    with tarfile.open(src, mode="r:*") as tf:
        while True:
            info = tf.next()
            if info is None: break
            print(info.name, info.pax_headers.get("hole", None))


def main():
    parser = argparse.ArgumentParser(
        description="Create a .tar archive with a mock version of a dataset")
    parser.add_argument("src", action="store", help="dataset to archive or archive to extract")
    parser.add_argument("-x", "--extract", action="store_true", help="extract an archive")
    parser.add_argument("-c", "--create", action="store_true", help="create archive (default)")
    parser.add_argument("-C", dest="root", action="store", help="root directory to use (default: current directory)")
    parser.add_argument("--debug", action="store_true", help="debugging output")
    parser.add_argument("-v", "--verbose", action="store_true", help="verbose output")
    args = parser.parse_args()

    log_format = "%(asctime)-15s %(levelname)s %(message)s"
    level = logging.WARN
    if args.debug:
        level = logging.DEBUG
    elif args.verbose:
        level = logging.INFO
    logging.basicConfig(level=level, stream=sys.stderr, format=log_format)

    if args.extract:
        do_extract(args.src, args.root)
    else:
        do_archive(args.src, args.root)

if __name__ == "__main__":
    main()
