#!/usr/bin/python3

import os
import sys
import subprocess
import json
import argparse
from inspect import cleandoc
import logging

log = logging.getLogger("main")

class Renderer:
    def __init__(self, srcdir, dstdir):
        self.srcdir = srcdir
        self.dstdir = dstdir

        # Jinja2 template engine
        from jinja2 import Environment, FileSystemLoader
        self.jinja2 = Environment(
            loader=FileSystemLoader([
                self.srcdir,
                self.dstdir,
            ]),
            autoescape=False,
            trim_blocks=True,
        )

    def render(self, fname):
        with open(fname, "rt") as fd:
            template = self.jinja2.from_string(fd.read())
        rendered = template.render()
        dst = fname[:-3]
        with open(dst, "wt") as fd:
            fd.write(rendered)
        log.info("rendered %s to %s", fname, dst)

    def update_testdoc(self, testdoc):
        testdoc = os.path.join(self.srcdir, "testdoc.json")
        try:
            with open(testdoc, "rt") as fd:
                old_data = json.load(fd)
        except FileNotFoundError:
            old_data = None

        testcase = os.path.join(self.srcdir, "../arki/tests/arki-test")
        stdout = subprocess.check_output([testcase, "--doc"], universal_newlines=True)
        new_data = json.loads(stdout)

        for d in new_data:
            d["doc"] = cleandoc(d["doc"])

        if old_data == new_data:
            return

        with open(testdoc, "wt") as fd:
            json.dump(new_data, fd, sort_keys=True, indent=1)


def main():
    parser = argparse.ArgumentParser(description="render arkimet documentation templates")
    parser.add_argument(
        "--verbose", "-v", action="store_true", help="verbose output")
    parser.add_argument(
        "--debug", action="store_true", help="debug output")
    parser.add_argument(
        "--srcdir", action="store", help="source directory (default, same as update script)")
    parser.add_argument(
        "--dstdir", action="store", help="destination directory (default, same as update script)")
    parser.add_argument(
        "--testdoc", action="store", help="update testdoc.json file")
    parser.add_argument(
        "src", nargs="?", help="file to render (default: all files in doc directory)")

    args = parser.parse_args()

    log_format = "%(asctime)-15s %(levelname)s %(message)s"
    level = logging.WARN
    if args.debug:
        level = logging.DEBUG
    elif args.verbose:
        level = logging.INFO
    logging.basicConfig(level=level, stream=sys.stderr, format=log_format)

    scriptdir = os.path.dirname(__file__)

    srcdir = args.srcdir or scriptdir
    dstdir = args.dstdir or scriptdir

    log.debug("source dir: %s", srcdir)
    log.debug("destination dir: %s", dstdir)

    renderer = Renderer(srcdir, dstdir)

    if args.testdoc:
        renderer.update_testdoc(args.testdoc)
    elif args.src:
        renderer.render(args.src)
    else:
        for root, dirs, files in os.walk("."):
            for f in files:
                if not f.endswith(".md.j2"): continue
                renderer.render(os.path.join(root, f))


if __name__ == "__main__":
    main()
