#!/usr/bin/python

# Filter metadata according to a match expression
#
# Copyright (C) 2007  ARPA-SIM <urpsim@smr.arpa.emr.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#
# Author: Enrico Zini <enrico@enricozini.com>

from metadata import Metadata
from matcher import Matcher
import sys

if len(sys.argv) == 1:
    print >>sys.stderr, "Usage:", sys.argv[0], "expression"
    print >>sys.stderr, "Print to standard output only those metadata read from standard input"
    print >>sys.stderr, "that match the given expression."
    sys.exit(1)

matcher = Matcher(sys.argv[1])
md = Metadata()

while md.read(sys.stdin):
    if matcher.match(md):
        md.write(sys.stdout)
