#!/bin/sh -e

BINDIR=`dirname $0`

. $BINDIR/testlib.sh

if [ $# -eq 0 ]
then
	setup
	trap cleanup EXIT

	importtest

#    cat << EOF > cpconfig
#[global]
#server.log_to_screen = False
#server.log_file = "arki-server.log"
#EOF

	if [ ! -z "$DO_SHELL" ]
	then
		echo "Running $CMD"
		arki-server $SERVER_OPTS --runtest="/bin/bash" conf
	else
		CMD=test-src
		if [ ! -z "$DEBUGGER" ] && [ -x $BINDIR/.libs/lt-$CMD ]
		then
			echo "Running $DEBUGGER $BINDIR/.libs/lt-$CMD $ARGS"
			arki-server $SERVER_OPTS --runtest="$DEBUGGER $BINDIR/.libs/lt-$CMD $ARGS" conf
		else
			echo "Running $DEBUGGER $CMD $ARGS"
			arki-server $SERVER_OPTS --runtest="$DEBUGGER $BINDIR/$CMD $ARGS" conf
		fi
	fi

	endtest
fi
