#!/bin/sh -e

BINDIR=`dirname $0`

. $BINDIR/testlib.sh

if [ $# == 0 ]
then
	setup
	trap cleanup EXIT

	importtest

#    cat << EOF > cpconfig
#[global]
#server.log_to_screen = False
#server.log_file = "arki-server.log"
#EOF

	if [ ! -z "$DO_SHELL" ]
	then
		echo "Running $CMD"
		arki-server1 -p 7117 --url="http://localhost:7117" --quiet --runtest="/bin/bash" conf
	else
		CMD=test-src
		if [ ! -z "$DEBUGGER" ] && [ -x $BINDIR/.libs/lt-$CMD ]
		then
			echo "Running $DEBUGGER $BINDIR/.libs/lt-$CMD $ARGS"
			arki-server1 -p 7117 --url="http://localhost:7117" --quiet --runtest="$DEBUGGER $BINDIR/.libs/lt-$CMD $ARGS" conf
		else
			echo "Running $DEBUGGER $CMD $ARGS"
			arki-server1 -p 7117 --url="http://localhost:7117" --quiet --runtest="$DEBUGGER $BINDIR/$CMD $ARGS" conf
		fi
	fi

	endtest
fi
