#!/bin/sh -e

BINDIR=`dirname $0`

. $BINDIR/testlib.sh

if [ $# -eq 0 ]
then
	setup
	trap cleanup EXIT

	importtest

#    cat << EOF > cpconfig
#[global]
#server.log_to_screen = False
#server.log_file = "arki-server.log"
#EOF

	if [ ! -z "$DO_SHELL" ]
	then
		echo "Running $CMD"
		arki-server $SERVER_OPTS --runtest="/bin/bash" conf
	else
        CMD=test-src
        echo "Running $DEBUGGER $CMD $ARGS"
        arki-server $SERVER_OPTS --runtest="libtool --mode=execute $DEBUGGER $BINDIR/$CMD $ARGS" conf
	fi

	endtest
fi
