#!/usr/bin/python

# Print to standard output the metadata summary with the contents of all the
# files in input.
#
# Copyright (C) 2007  ARPA-SIM <urpsim@smr.arpa.emr.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#
# Author: Enrico Zini <enrico@enricozini.com>

from metadata import Metadata
from datetime import datetime
import sys

md = Metadata()

# Summarised reference time range
tbegin = None
tend = None
found = 0
origins = set()

while md.read(sys.stdin):
    # Summarise the reference time information we find
    for ti in md.get_reference_time_info():
        if isinstance(ti, datetime):
            if tbegin == None or tbegin > ti:
                tbegin = ti
            if tend == None or tend < ti:
                tend = ti
        else:
            if tbegin == None or tbegin > ti[0]:
                tbegin = ti[0]
            if tend == None or tend < ti[1]:
                tend = ti[1]
    for o in md.get_origins():
        origins.add(o)
    found += 1

if found > 0:
    summary = Metadata()
    summary.create()
    summary.set_reference_time_info( (tbegin, tend) )
    summary.set_origins(origins)
    summary.write(sys.stdout)
