#!/bin/sh -e

test -z "$ARGS" || exit 0

BINDIR=`dirname $0`

. $BINDIR/testlib.sh

setup
trap cleanup EXIT

echo -n "Testing arki-check"

importtest

echo "archive age = 1" >> test200/config

# Try checking a dataset
runtest "arki-check test200 --fix"
runtest "arki-check --repack --fix test200"
runtest "test -e test200/.archive/last/2007/07-08.grib"
runtest "arki-check --unarchive=2007/07-08.grib test200"
runtest "test -e test200/2007/07-08.grib"

runtest "arki-query --yaml '' test200/ | grep -q 'test200/2007/07-08.grib:0+7218'"

# Reproduce issue 57
mkdir -p issue57/2016
cat > issue57/config <<EOF
type = ondisk2
filter = area:VM2,
step = daily
unique = reftime, area, product
EOF
echo "201610050000,12626,139,70,,,000000000" > issue57/2016/10-05.vm2
runtest "arki-check -f issue57"
arki-query '' issue57 > issue57/todelete.md
runtest "test -s issue57/todelete.md"
runtest "arki-check --remove=issue57/todelete.md issue57"
arki-query '' issue57 > issue57/todelete.md
runtest "test -S issue57/todelete.md"


testtotals

exit $BADCOUNT
