#!/bin/sh -e

test -z "$ARGS" || exit 0

BINDIR=`dirname $0`

. $BINDIR/testlib.sh

setup
trap cleanup EXIT

importtest
runserver

echo -n "Testing arki-mergeconf"

# Try passing files to the postprocessor
runtest "arki-mergeconf $SERVER_URL"

testtotals

exit $BADCOUNT
