#!/bin/sh -e

test -z "$ARGS" || exit 0

BINDIR=`dirname $0`

. $BINDIR/testlib.sh

if [ $# -eq 0 ]
then
    setup
    trap cleanup EXIT

    importtest

#    cat << EOF > cpconfig
#[global]
#server.log_to_screen = False
#server.log_file = "arki-server.log"
#EOF

    rm -f as-access.log as-error.log
    arki-server -p 7117 --url="http://localhost:7117" --accesslog="as-access.log" --errorlog="as-error.log" --runtest="$BINDIR/`basename $0` run" conf

    endtest
elif [ $1 = 'run' ]
then
    BASEURL=http://localhost:7117

    echo -n "Testing arki-server "

    # Check uploading files
    runtest "arki-query --postproc=checkfiles --postproc-data=/dev/null '' $BASEURL/dataset/test200"
    runtest "arki-query --postproc=checkfiles --postproc-data=/dev/null --postproc-data=/dev/null '' $BASEURL/dataset/test200"

    # Check that something gets logged
    runtest "test -s as-access.log"
    runtest "test -s as-error.log"

    testtotals

    exit $BADCOUNT
fi
