#!/bin/sh -e

test -z "$ARGS" || exit 0

BINDIR=`dirname $0`

. $BINDIR/testlib.sh

setup
trap cleanup EXIT

importtest
runserver

echo -n "Testing arki-mergeconf"

runtest "arki-mergeconf $SERVER_URL"
runtest "arki-mergeconf $SERVER_URL > test_arki_mergeconf.conf && grep -v [error] test_arki_mergeconf.conf"
runtest "arki-mergeconf --ignore-system-datasets $SERVER_URL > test_arki_mergeconf.conf && ! grep '\[error\]' test_arki_mergeconf.conf"

testtotals

exit $BADCOUNT
