#!/bin/sh -e

BINDIR=`dirname $0`

. $BINDIR/testlib.sh

if [ $# == 0 ]
then
    setup

    importtest

    cat << EOF > cpconfig
[global]
server.log_to_screen = False
server.log_file = "arki-server.log"
EOF

    arki-server -p 7117 --cpconfig=cpconfig --runtest="$BINDIR/`basename $0` run" conf

    endtest
elif [ $1 == 'run' ]
then
    BASEURL=http://localhost:7117

    echo -n "Testing arki-server "

    # Get the config
    runtest "curl -s $BASEURL/config > serverconfig"
    runtest "grep -q 'test200' serverconfig"
    runtest "grep -q 'test80' serverconfig"
    runtest "grep -q 'error' serverconfig"
    runtest "grep -q 'path *= *http://' serverconfig"

    # Expand a query
    runtest "curl --data-urlencode query='origin:GRIB1,200;product:t' -s $BASEURL/qexpand > tmpfile && grep -q 'origin:GRIB1,200; product:GRIB1,200,2,11 or GRIB1,98,128,130 or GRIB1,98,128,167 or GRIB1,200,200,11' tmpfile"

    # Get the server alias database
    runtest "curl -s $BASEURL/aliases > tmpfile && grep -q '\[origin\]' tmpfile"

    # Get the summary from all datasets
    runtest "curl -s $BASEURL/dataset/test200/summary | head -c 2 | grep -q ^SU"
    runtest "curl -s $BASEURL/dataset/test80/summary | arki-dump >tmpfile && grep -q SummaryItem tmpfile"
    runtest "curl -s $BASEURL/dataset/error/summary | arki-dump >tmpfile && grep -q SummaryItem tmpfile"

    # Try a normal query
    runtest "curl -s $BASEURL/dataset/error/query | arki-dump >tmpfile && grep -q ^Origin tmpfile"
    runtest "curl -d query=origin:GRIB1,200 -s $BASEURL/dataset/test200/query | arki-dump | testnonempty"
    runtest "curl -d query=origin:GRIB1,80 -s $BASEURL/dataset/test200/query | arki-dump | testempty"
    runtest "curl -d style=postprocess -d command='say ciao' -s $BASEURL/dataset/test200/query | testequals 'ciao'"

    testtotals

    exit $BADCOUNT
fi
