#!/bin/sh -e

test -z "$ARGS" || exit 0

BINDIR=`dirname $0`

. $BINDIR/testlib.sh

setup
trap cleanup EXIT

importtest

echo -n "Testing arki-scan"

# Try scanning a GRIB1 file
runtest "arki-scan --yaml inbound/test.grib1 | grep -q ^Origin"

# Try scanning a BUFR file
if grep -q "HAVE_DBALLE 1" $TOP_SRCDIR/config.h
then
	runtest "arki-scan --yaml inbound/test.bufr | grep -q ^Origin"
fi

testtotals

exit $BADCOUNT
